"""initial_schema_with_credits_and_coupons

Revision ID: 61622c41f579
Revises: ba24b7fa87df
Create Date: 2026-03-23 13:57:36.497914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61622c41f579'
down_revision: Union[str, None] = 'ba24b7fa87df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
